### ISSUE TITLE
Function wpdb::prepare was called incorrectly.

### ISSUE THREAD

**Issue by reneaye** [ControlZetaDigital/polylang-tcopro#1]
Not a REAL issue, but I get the following message:

**Function wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. (This message was added in version 3.9.0.)**

This happens i.e. here:
includes/class-polylang-tcopro-integration.php
line 168

As far as I understood it does make sense to use the stringf like syntax of the prepare() method, cause this way it uses some security and sanitizing checks. If you use PHPs curly syntax fro string interpolation these checks get circumvented.

**Comment by ControlZetaDigital** [comment]
You're right, using "prepare" in this case is not necessary since I'm not using placeholders, and I'm not using variables obtained from users that could contain SQL injections. I'll fix it when I have some time. Thanks!

**Comment by ControlZetaDigital** [comment]
Issue corrected in 1.1.2 :)

**Comment by reneaye** [comment]
Great! Thank you ;)
